name: vlm
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pip:
      - vllm>=0.11.0
      - transformers
      - torch
      - torchvision
      - torchaudio
      - pillow
      - pillow-heif
      - pymupdf
      - datasets
      - huggingface-hub
      - srsly
      - typer
      - tqdm
